"""
Render a DriftReport to the terminal, Markdown, or JSON.
"""
import json
from datetime import datetime
from typing import Optional

from shellcolorize import Color
from .diff import DriftReport, Change

_SEV_COLOR = {
    'CRITICAL': Color.RED,
    'WARNING':  Color.YELLOW,
    'INFO':     Color.CYAN,
}

_SEV_ICON = {
    'CRITICAL': '⛔',
    'WARNING':  '⚠ ',
    'INFO':     '·',
}

_KIND_SYMBOL = {
    'added':   '+',
    'removed': '-',
    'changed': '~',
}

_CATEGORIES = ['ports', 'users', 'crons', 'services', 'packages']
_CAT_LABELS = {
    'packages': 'Packages',
    'ports':    'Ports',
    'users':    'Users',
    'crons':    'Cron Jobs',
    'services': 'Services',
}


def _header() -> None:
    title = 'infradrift  ·  drift report'
    w = len(title) + 6
    print()
    print(f"  {Color.CYAN}╔{'═' * w}╗{Color.RESET}")
    print(f"  {Color.CYAN}║{Color.RESET}  {Color.BOLD}{Color.CYAN}{title}{Color.RESET}  {Color.CYAN}║{Color.RESET}")
    print(f"  {Color.CYAN}╚{'═' * w}╝{Color.RESET}")
    print()


def _meta_line(label: str, meta: dict) -> None:
    ts = meta.get('captured_at', '?')
    host = meta.get('hostname', '?')
    print(f"  {Color.DIM}{label:<10}{Color.RESET} {ts}  ({host})")


def _section(label: str) -> None:
    print()
    print(f"  {Color.CYAN}── {label} {'─' * max(0, 38 - len(label))}{Color.RESET}")


def _change_line(c: Change) -> None:
    color  = _SEV_COLOR.get(c.severity, '')
    icon   = _SEV_ICON.get(c.severity, ' ')
    sym    = _KIND_SYMBOL.get(c.kind, ' ')
    detail = f"  {Color.DIM}{c.detail}{Color.RESET}" if c.detail else ''
    print(f"  {color}{icon} {sym}  {c.description}{Color.RESET}{detail}")


def render_terminal(report: DriftReport) -> None:
    _header()
    _meta_line('Baseline', report.baseline_meta)
    _meta_line('Current', report.current_meta)
    print()

    if report.is_clean:
        print(f"  {Color.GREEN}✔  No drift detected — server state matches baseline.{Color.RESET}")
        print()
        return

    # Print by category in logical order
    by_cat = {}
    for c in report.changes:
        by_cat.setdefault(c.category, []).append(c)

    for cat in _CATEGORIES:
        changes = by_cat.get(cat, [])
        if not changes:
            continue
        _section(_CAT_LABELS.get(cat, cat))
        for c in changes:
            _change_line(c)

    # Summary footer
    print()
    print(f"  {'─' * 42}")
    total = len(report.changes)
    crit  = len(report.critical)
    warn  = len(report.warnings)
    info  = len(report.info)
    parts = []
    if crit: parts.append(f"{Color.RED}{crit} critical{Color.RESET}")
    if warn: parts.append(f"{Color.YELLOW}{warn} warning{'s' if warn > 1 else ''}{Color.RESET}")
    if info: parts.append(f"{Color.CYAN}{info} info{Color.RESET}")
    print(f"  {Color.BOLD}{total} change{'s' if total != 1 else ''} detected{Color.RESET}"
          + (f"  ({', '.join(parts)})" if parts else ''))
    print()


def render_markdown(report: DriftReport) -> str:
    lines = []
    ts_now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    lines += [
        "# infradrift — Drift Report",
        "",
        f"| | |",
        f"|---|---|",
        f"| **Baseline** | {report.baseline_meta.get('captured_at','?')}  ({report.baseline_meta.get('hostname','?')}) |",
        f"| **Current**  | {report.current_meta.get('captured_at','?')}  ({report.current_meta.get('hostname','?')}) |",
        f"| **Generated** | {ts_now} |",
        f"| **Changes** | {len(report.changes)} ({len(report.critical)} critical, {len(report.warnings)} warnings, {len(report.info)} info) |",
        "",
        "---",
        "",
    ]

    if report.is_clean:
        lines += ["## ✅ No drift detected", "", "Server state matches baseline.", ""]
        return '\n'.join(lines)

    by_cat = {}
    for c in report.changes:
        by_cat.setdefault(c.category, []).append(c)

    _icons = {'CRITICAL': '⛔', 'WARNING': '⚠️', 'INFO': 'ℹ️'}
    _syms  = {'added': '+', 'removed': '−', 'changed': '~'}

    for cat in _CATEGORIES:
        changes = by_cat.get(cat, [])
        if not changes:
            continue
        lines += [f"## {_CAT_LABELS.get(cat, cat)}", ""]
        for c in changes:
            icon = _icons.get(c.severity, '')
            sym  = _syms.get(c.kind, ' ')
            detail = f" _{c.detail}_" if c.detail else ''
            lines.append(f"- {icon} `{sym}` {c.description}{detail}")
        lines.append("")

    lines += ["---", "", f"*Generated by [infradrift](https://github.com/serber1990/infradrift) at {ts_now}*"]
    return '\n'.join(lines)


def render_json(report: DriftReport) -> str:
    return json.dumps({
        'baseline_meta': report.baseline_meta,
        'current_meta':  report.current_meta,
        'summary': {
            'total':    len(report.changes),
            'critical': len(report.critical),
            'warnings': len(report.warnings),
            'info':     len(report.info),
        },
        'changes': [
            {
                'category':    c.category,
                'kind':        c.kind,
                'severity':    c.severity,
                'description': c.description,
                'detail':      c.detail,
            }
            for c in report.changes
        ],
    }, indent=2)
